/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface Ds1List {
    }
    interface Ds1Listitem {
        /**
          * The checked state of the component.
         */
        "checked": boolean;
        "checkedHandler": () => Promise<void>;
        "keyDownHandler": (keyCode: any) => Promise<void>;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLDs1ListElement extends Components.Ds1List, HTMLStencilElement {
    }
    var HTMLDs1ListElement: {
        prototype: HTMLDs1ListElement;
        new (): HTMLDs1ListElement;
    };
    interface HTMLDs1ListitemElement extends Components.Ds1Listitem, HTMLStencilElement {
    }
    var HTMLDs1ListitemElement: {
        prototype: HTMLDs1ListitemElement;
        new (): HTMLDs1ListitemElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "ds1-list": HTMLDs1ListElement;
        "ds1-listitem": HTMLDs1ListitemElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface Ds1List {
    }
    interface Ds1Listitem {
        /**
          * The checked state of the component.
         */
        "checked"?: boolean;
        /**
          * Qui posso scrivere la doc dell'evento.
         */
        "onChecked"?: (event: CustomEvent<any>) => void;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "ds1-list": Ds1List;
        "ds1-listitem": Ds1Listitem;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ds1-list": LocalJSX.Ds1List & JSXBase.HTMLAttributes<HTMLDs1ListElement>;
            "ds1-listitem": LocalJSX.Ds1Listitem & JSXBase.HTMLAttributes<HTMLDs1ListitemElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
